### ISSUE TITLE
toString versions of print functions

### ISSUE THREAD

**Issue by TysonMN** [hedgehogqa/fsharp-hedgehog#226]
I see three functions that print:
1. [Gen.printSample](https://github.com/hedgehogqa/fsharp-hedgehog/blob/043b4648b6f8aaa590a35a13ee852e8a240e06d5/src/Hedgehog/Gen.fs#L547-L555),
2. [Property.print](https://github.com/hedgehogqa/fsharp-hedgehog/blob/043b4648b6f8aaa590a35a13ee852e8a240e06d5/src/Hedgehog/Property.fs#L411-L414), and
3. [Property.print'](https://github.com/hedgehogqa/fsharp-hedgehog/blob/043b4648b6f8aaa590a35a13ee852e8a240e06d5/src/Hedgehog/Property.fs#L405-L408).

As I explore the codebase and try to understand how things work, I would find it more convenient if a variant for each of these functions existed that returns a string (instead of directly printing that string).  For example, while debugging, I would prefer to compute that string, assign it to a local variable, and view its value in the debugger.

Would it be ok for each of these printing functions to add an additional function that returns the string currently being printed?

**Comment by moodmosaic** [comment]
That would be good idea :+1: 

FTR, some of the stuff in F# Hedgehog existed before the Haskell version comes out (in this case that's why there's no such function for rendering a string) but the ultimate goal is to keep in sync at least `Gen`, `Tree`, and `Shrink` with Haskell.

If you're willing to work on it, it'd be nice to follow the same style and naming as in the Haskell codebase, where for example `printTree` ends up calling [`renderTree`](https://github.com/hedgehogqa/haskell-hedgehog/blob/7030059c089b45429c9ed23f37971e1b5334dc2e/hedgehog/src/Hedgehog/Internal/Gen.hs#L1764) internally (which is the function that returns the string you want).

**Comment by TysonMN** [comment]
I like this goal and am happy to follow the same style and naming as in the Haskell codebase.

As I gain more experience with this codebase, I will just directly create a PR when I want to add a feature that already exists in the Haskell codebase.

**Comment by moodmosaic** [comment]
Great, @TysonMN :100:
