### ISSUE TITLE
Gen registration and creation?

### ISSUE THREAD

**Issue by AnthonyLloyd** [hedgehogqa/fsharp-hedgehog#93]
Do you plan on this kind of feature? Gen.type<'a> from already registered Gen types.

**Comment by moodmosaic** [comment]
I find this a *very* interesting question.

The plan is to have the F# version in line with the Haskell one. In the Haskell version there are no `Arbitrary` instances (and therefore no orphans) and so there's no reason to deviate in F#.

Actually, in F#, things are even worse because there's currently no direct support for type classes, and you'd have to simulate them instead (like FsCheck [does](https://github.com/fscheck/FsCheck/blob/master/src/FsCheck/TypeClass.fs)—[which, in my opinion, was a design mistake](https://github.com/fscheck/FsCheck/issues/198#issuecomment-183880822)).

Even Kurt Schelfthout, the author of FsCheck (that currently supports what you describe), was [not sure if `Arbitrary` is worth keeping in FsCheck vNext](https://github.com/fscheck/FsCheck/issues/198#issuecomment-183922895).

To simulate the `Arbitrary` registration mechanism in F# Hedgehog, you may use a dictionary and write a reflection-based generator using [TypeShape](), similar to [this](http://www.fssnip.net/7RA/title/Generic-POCO-generators-for-FsCheck) one—but that can't be part of F# Hedgehog.

/cc @jystic

**Comment by AnthonyLloyd** [comment]
Yeah, I've never liked Arbitrary, it just gets in the way and seems a bit...arbitrary.

I was thinking something like [Infers](https://github.com/Infers/Infers).

I love the automatic shrinking by default but would need to be able to gen DUs etc automatically to be able to use it in testing.

**Comment by moodmosaic** [comment]
I'd be nice to see an example of this using Infers 👍 Apart from that, I think we should close this issue. We can still add comments, and even reopen it in the future, if necessary.

**Comment by AnthonyLloyd** [comment]
Sure

**Comment by moodmosaic** [comment]
@AnthonyLloyd 

>I love the automatic shrinking by default but would need to be able to gen DUs etc automatically to be able to use it in testing.

I wrote an example in https://github.com/hedgehogqa/fsharp-hedgehog/issues/133#issuecomment-336029776 where you can automatically generate DUs and pretty much any other type.

**Comment by AnthonyLloyd** [comment]
Great. I love hedgehog and have been using it on a nested DU domain model.

Interestingly the automatic gen of this model from FsCheck is wrong for me because it generates each top level case with the same probability etc. I really need each leaf case to be generated with the same probability. So coded the gen.

I'd be interested in adding hedgehog to Expecto if the automatic gen was added and we were certain that FsCheck would never be refactored to work as hedgehog does without `Arbitrary`.

**Comment by moodmosaic** [comment]
FWIW, @cmeeren provided an updated, configurable, version of arbitrary POCO generartion in https://github.com/hedgehogqa/fsharp-hedgehog/issues/133#issuecomment-336843174.
